// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABHQxiu1mJ863KjI8RDNBYl7VozcrEUAU',
    appId: '1:680105274814:web:ba6c3b8b055ed381b55def',
    messagingSenderId: '680105274814',
    projectId: 'florafauna-8ff6a',
    authDomain: 'florafauna-8ff6a.firebaseapp.com',
    storageBucket: 'florafauna-8ff6a.firebasestorage.app',
    measurementId: 'G-EL9744KG74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxF1ffu7xN4BpE71KeeCLTwLBr1RZzsgA',
    appId: '1:680105274814:android:1de03f6039c2d61cb55def',
    messagingSenderId: '680105274814',
    projectId: 'florafauna-8ff6a',
    storageBucket: 'florafauna-8ff6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwdJwtHruxDYatfTYlSJ9SWJJeUf7Yexg',
    appId: '1:680105274814:ios:4c2d67a240d8fc1bb55def',
    messagingSenderId: '680105274814',
    projectId: 'florafauna-8ff6a',
    storageBucket: 'florafauna-8ff6a.firebasestorage.app',
    iosBundleId: 'com.example.florafauna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwdJwtHruxDYatfTYlSJ9SWJJeUf7Yexg',
    appId: '1:680105274814:ios:4c2d67a240d8fc1bb55def',
    messagingSenderId: '680105274814',
    projectId: 'florafauna-8ff6a',
    storageBucket: 'florafauna-8ff6a.firebasestorage.app',
    iosBundleId: 'com.example.florafauna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABHQxiu1mJ863KjI8RDNBYl7VozcrEUAU',
    appId: '1:680105274814:web:19f616b8f37ab01ab55def',
    messagingSenderId: '680105274814',
    projectId: 'florafauna-8ff6a',
    authDomain: 'florafauna-8ff6a.firebaseapp.com',
    storageBucket: 'florafauna-8ff6a.firebasestorage.app',
    measurementId: 'G-VETH0VHW6E',
  );

}